### ISSUE TITLE
Поддержка нескольких типов авторизации в одном процессе

### ISSUE THREAD

**Issue by yura-shutkin** [leominov/vault-reliability-exporter#1]
Доброго дня,
Прошу добавить возможность авторизовываться не только через userpass, но и через LDAP бэкенд

**Comment by leominov** [comment]
Сейчас метод авторизации и креды передаются ключами:

```
  -vault.auth-login string
    	Vault user's login.
  -vault.auth-method string
    	Vault user's auth method. (default "userpass")
  -vault.auth-password string
    	Vault user's password.
```

**Comment by yura-shutkin** [comment]
Поправка. Требуется поддержка нескольких типов авторизации в одном экспортере одновременно.

**Comment by leominov** [comment]
@yura-shutkin нужен подопытный :)

**Comment by leominov** [comment]
Done
