### ISSUE TITLE
Поддержка кастомных лейблов

### ISSUE THREAD

**Issue by yura-shutkin** [leominov/vault-reliability-exporter#2]
Доброго дня,
Прошу добавить возможность указывать кастомные лейблы, для отправки из в пушгейтвей. Например окружение, сервис, группа

**Comment by leominov** [comment]
https://github.com/leominov/vault-reliability-exporter/releases/tag/v1.0.2

Передавать лейблы со значением нужно через флаг `labels`, например, `--labels=env=prod`.
