### ISSUE TITLE
Сделать запись опциональной в секреты

### ISSUE THREAD

**Issue by yura-shutkin** [leominov/vault-reliability-exporter#6]
Авторизуемся под несколькими УЗ
под каждой проверяем 2 действия:
* Авторизация
* Запись/чтение

Изменения:
* Если secret_path указан, но не указан secret_data, то пишем дефолтные значения по указанному пути
* Если secret_path не указан, только авторизуемся

**Comment by leominov** [comment]
https://github.com/leominov/vault-reliability-exporter/releases/tag/v2.1.0

**Comment by leominov** [comment]
Done
