### ISSUE TITLE
feature request: Добавить возможность отзыва токена

### ISSUE THREAD

**Issue by yura-shutkin** [leominov/vault-reliability-exporter#7]
Доброго дня,
Прошу добавить флаг revoke_token

По умолчанию True

Для LDAP авторизационного бэкенда не возможно задать отдельной УЗ время жизни токена, это портит статистику

**Comment by yura-shutkin** [comment]
https://www.vaultproject.io/api/auth/token/index.html#revoke-a-token

**Comment by leominov** [comment]
Попробуй эту сборку:

[vault-reliability-exporter-2.2.0.linux-amd64.tar.gz](https://github.com/leominov/vault-reliability-exporter/files/3661068/vault-reliability-exporter-2.2.0.linux-amd64.tar.gz)

Пример использования опции по ревоку в примере конфига.

**Comment by leominov** [comment]
Done
